First Commit
darkjinung/projet-industriel-ecp17 pull request #23
Opened 2017-10-16 23:49 UTC by AmineIzanami

First Commit for #22

2017-10-17 10:28 UTC, darkjinung approved these changes
Correcting grammar

2017-10-17 12:13 UTC, darkjinung requested changes
Look at comments for more information

2017-10-17 12:13 UTC, darkjinung commented on State of the Art/Semantic Analysis/StateofArt_SyntacticandSemanticAnalyses.md
> +To represent the meaning of a sentence we need a more precise method because words have multiple meanings so the solutions is the use of formal languages.
"a ~~more~~ precise"
"because words **can** have multiple meanings **. A solution**"

2017-10-17 12:13 UTC, darkjinung commented on State of the Art/Semantic Analysis/StateofArt_SyntacticandSemanticAnalyses.md
> +There is varied types of knowledge relevant to natural language understanding:
"There **are various** types of"

2017-10-17 12:13 UTC, darkjinung commented on State of the Art/Semantic Analysis/StateofArt_SyntacticandSemanticAnalyses.md
> +**Semantic knowledge**: how words have "meaning"; how words have reference (denotation) and associated concepts (connotations)
I don't understand the sentence. You mean "Meaning" as "denoation + connotation"?
If YES:
~~; how words have~~ **: its** reference (denotation) and associated.......

2017-10-17 12:13 UTC, darkjinung commented on State of the Art/Semantic Analysis/StateofArt_SyntacticandSemanticAnalyses.md
> +**Pragmatic knowledge**: "how sentences are used in different situations and how use affects the interpretation of the sentence," this involves the intentions and context of the conversation.
"and how **their** use affects"
"involves" *wrong word?* maybe "**takes into account**" ?

2017-10-17 12:13 UTC, darkjinung commented on State of the Art/Semantic Analysis/StateofArt_SyntacticandSemanticAnalyses.md
> +**World knowledge**: general knowledge about for example, other users beliefs and goals in a conversation.
"~~about~~ **such as,** for example,"

2017-10-17 12:13 UTC, darkjinung commented on State of the Art/Semantic Analysis/StateofArt_SyntacticandSemanticAnalyses.md
> +Starting with a sentence in natural language , the result of syntacticc analysis will yield a syntatic representation ( often displayed in a tree diagram),
**typo**: One too many "c" in "Syntacticc"

2017-10-17 12:13 UTC, darkjinung commented on State of the Art/Semantic Analysis/StateofArt_SyntacticandSemanticAnalyses.md
> +the resuslt of that representation wukk tuekd ti tge kigucak firle if tge sebtebce n kiguck frl us ysed ti caotyre seblabtuc lebaubg abd depict this eaning independent of any such context ,
**typo**: "resuslt"
**WTF?** "wukk tuekd ti tge kigucak firle if tge sebtebce n kiguck frl us ysed ti caotyre seblabtuc lebaubg abd depict"

2017-10-17 12:13 UTC, darkjinung commented on State of the Art/Semantic Analysis/StateofArt_SyntacticandSemanticAnalyses.md
> +## What is a *good grammar*
Should be "What is good grammar"

2017-10-17 12:13 UTC, darkjinung commented on State of the Art/Semantic Analysis/StateofArt_SyntacticandSemanticAnalyses.md
> +then we need a general knowledge representation which allows a contextual interpretaiton of the context free form analyss and logical form
**typo**: "analyss"

2017-10-17 12:13 UTC, darkjinung commented on State of the Art/Semantic Analysis/StateofArt_SyntacticandSemanticAnalyses.md
> +**Parser**: maps  natural language to their suntactic stucture on representation and their logical form ( uses the rules of gammar and word meanings )
Spelling Error (**SE**): "suntatic"

2017-10-17 12:13 UTC, darkjinung commented on State of the Art/Semantic Analysis/StateofArt_SyntacticandSemanticAnalyses.md
> +**Contextual interpretation** : maps the logical form to it's final knowledge representation
Grammatical error (**GE**) "it's" --> "its"

2017-10-17 12:13 UTC, darkjinung commented on State of the Art/Semantic Analysis/StateofArt_SyntacticandSemanticAnalyses.md
> +To accomplish the semantic and syntactic analysis , there will be common elements in any such parsing :
Review last part of sentence

2017-10-17 12:13 UTC, darkjinung commented on State of the Art/Semantic Analysis/StateofArt_SyntacticandSemanticAnalyses.md
> +1. They'll be a grammar ( the legal ways for combining the units - syntactically and semantically ) to result in other constituents,
"There" instead of "they"?

2017-10-17 12:13 UTC, darkjinung commented on State of the Art/Semantic Analysis/StateofArt_SyntacticandSemanticAnalyses.md
> +2. The processos will have an algorithm using the rules of the grammar
**typo**: "processos"

2017-10-17 12:13 UTC, darkjinung commented on State of the Art/Semantic Analysis/StateofArt_SyntacticandSemanticAnalyses.md
> +3. an orcle , a mechanisme of resolvng ambiguities
**SE**: "mechanisme" (no "e")
**typo**: "resolvng"

2017-10-17 12:13 UTC, darkjinung commented on State of the Art/Semantic Analysis/StateofArt_SyntacticandSemanticAnalyses.md
> +A good grammar have to be:
~~A~~

2017-10-17 12:13 UTC, darkjinung commented on State of the Art/Semantic Analysis/StateofArt_SyntacticandSemanticAnalyses.md
> +A parsing thechnique is the mehode of analyzing a sentence to dermine it's structure , in accordance with grammar it may adope a top-down or bottom-up strategy
**typo**: "thechnique"
**typo**: "dermine"
**GA**: "it's" should be "its"
**SE/typo**: "adpoe" should be "adopt"

2017-10-17 12:13 UTC, darkjinung commented on State of the Art/Semantic Analysis/StateofArt_SyntacticandSemanticAnalyses.md
> +	1. noise-disposal : scans a sentence looking for selected words, which are in its defined vocabulary. During the process any words not in the range of those the computer is looking for are considere
Need re-phrasing till ";"
**typo**: "somehitng"

2017-10-17 12:13 UTC, darkjinung commented on State of the Art/Semantic Analysis/StateofArt_SyntacticandSemanticAnalyses.md
> +		Exemple : the user want to "Sort the 10 first files" ; the computer will take the action "Sort" as the main action without any condition and will sort all the files.
**GE**: "want" need to be "wants"
**GE**: "Sort the first 10 files"

2017-10-17 13:30 UTC, AmineIzanami commented on State of the Art/Semantic Analysis/StateofArt_SyntacticandSemanticAnalyses.md
> +To represent the meaning of a sentence we need a more precise method because words have multiple meanings so the solutions is the use of formal languages.
a word, by definition, has always multiple meaning, and in order to use NLP, the solution is the use of formal languages ( it's the first step )

2017-10-17 13:31 UTC, AmineIzanami commented on State of the Art/Semantic Analysis/StateofArt_SyntacticandSemanticAnalyses.md
> +**Pragmatic knowledge**: "how sentences are used in different situations and how use affects the interpretation of the sentence," this involves the intentions and context of the conversation.
I think "involves" it's more accurate

2017-10-17 13:33 UTC, AmineIzanami commented on State of the Art/Semantic Analysis/StateofArt_SyntacticandSemanticAnalyses.md
> +the resuslt of that representation wukk tuekd ti tge kigucak firle if tge sebtebce n kiguck frl us ysed ti caotyre seblabtuc lebaubg abd depict this eaning independent of any such context ,
Like really i dont know, where that sentence cames from 🍡

2017-10-17 14:02 UTC, darkjinung commented on State of the Art/Semantic Analysis/StateofArt_SyntacticandSemanticAnalyses.md
> +To represent the meaning of a sentence we need a more precise method because words have multiple meanings so the solutions is the use of formal languages.
I don't understand your comment. At all.

Here are the reasons for my previous comment:
"a ~~more~~ precise": if you use the word "more" you need to compare it to something (so use "than" followed by example that is not precise enought). When we read that part we ask ourselfs "more presice than what?" and the answer is not given by your sentence.
"[...] **can** have multiuple meanings": Words don't have necessarily two or more meaning, they can have only one.
"[...] multiple meanings ~~so the solutions~~ **. A solution**": You only talk about one solution, the use of formal languages. Unless you talk about multiple solutions you need to keep "solution" in singular.

2017-10-17 14:07 UTC, darkjinung commented on State of the Art/Semantic Analysis/StateofArt_SyntacticandSemanticAnalyses.md
> +**Pragmatic knowledge**: "how sentences are used in different situations and how use affects the interpretation of the sentence," this involves the intentions and context of the conversation.
You cannot use this verbe in this context
www.oxfordlearnersdictionaries.com/definition/english/involve

2017-10-18 10:19 UTC, darkjinung approved these changes

2017-10-18 10:19 UTC, merged