Issue/#5
darkjinung/projet-industriel-ecp17 pull request #9
Opened 2017-10-05 20:55 UTC by amineds

review and validate

2017-10-05 21:11 UTC, AmineIzanami requested changes
you have a typo it's "**implements**" and not "implemnts"

2017-10-06 09:01 UTC, amineds commented
Validate for merge plz

2017-10-06 11:34 UTC, AmineIzanami approved these changes

2017-10-06 11:35 UTC, AmineIzanami commented
I approved your changes you can merge now, thank you

2017-10-08 16:06 UTC, merged